### ISSUE TITLE
The inline style in main-header > sub needs to be removed

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/ip.wsu.edu#12]
<span class="sub-header-default" style="font-size: 84px;">Future Students</span>

**Comment by slocker3** [comment]
I see, this is generated by display:flex -- a media-query should probably be used to introduce this at the appropriate sizes.

**Comment by slocker3** [comment]
What is setting the inline style for the sub?

**Comment by jeremyfelt** [comment]
Fixed by removal of fittext in #14
