### ISSUE TITLE
color palette choices

### ISSUE THREAD

**Issue by jbickelhaupt** [washingtonstateuniversity/ip.wsu.edu#4]
We need to modify the WSU Color Palette so that we only have the following choices when in the WP page editor:
1. crimson (#981e32)
2. blue1 (#4f868e)
3. gray1 (#8d959a)
4. blue2 (#2f5055)
5. gray2 (#464e54)

Please see me if you have questions. Thanks!

**Comment by jeremyfelt** [comment]
Fixed and deployed via #5
